displayName=Green Combat Achievements
author=camjewell11
description=Highlights a boss's name green in the Combat Achievements list once all of its tasks are completed
tags=combat achievements,boss,highlight,green,ca
version=
plugins=com.greencombatachievements.GreenCombatAchievementsPlugin
build=standard