displayName=Green Combat Achievements Menu
author=ThePrestiege
description=Highlights a boss's name green in the Combat Achievements list once all of its tasks are completed
tags=combat achievements,boss,highlight,green,ca,combat,achievement,
version=1.0
plugins=com.greencombatachievements.GreenCombatAchievementsPlugin
build=standard